#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
/config/www/tt-rss/{themes.local,plugins.local}

# create symlinks
symlinks=( \
/var/www/html/config.php \
/var/www/html/themes.local \
/var/www/html/plugins.local
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/tt-rss/"$(basename "$i")" "$i"
done

# permissions
chown -R abc:abc \
	/config/www \
    /var/www/
