#!/usr/bin/with-contenv bash

# install tt-rss
if [ ! -d /config/www/tt-rss ]; then
	TT_RSS_VERSION=$(cat /version.txt)
	mkdir -p /config/www/tt-rss
	echo "fetching tt-rss files, this may take a little while"
	curl -o /tmp/tt-rss.tar.gz -L https://git.tt-rss.org/git/tt-rss/archive/${TT_RSS_VERSION}.tar.gz
	tar xf /tmp/tt-rss.tar.gz -C /config/www/tt-rss --strip-components=1
	rm -f /tmp/tt-rss.tar.gz
fi

# permissions
chown -R abc:abc \
	/config/www
