#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
/config/www/tt-rss/{themes.local,plugins.local}

# create symlinks
symlinks=( \
/var/www/html/config.php \
/var/www/html/themes.local \
/var/www/html/plugins.local
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/tt-rss/"$(basename "$i")" "$i"
done


# config.php file setup
if [ "${DB_USER}" ];
	then
	echo "DB_USER set, injecting TT-RSS config"

    if [ ! -f /config/www/tt-rss/config.php ];
        then
	    echo "Creating config.php from the dist file"
        cp /var/www/html/config.php-dist /config/www/tt-rss/config.php
    fi

    [[ "${DB_TYPE}" ]] && sed -i "s|\s*define('DB_TYPE',.*|\tdefine('DB_TYPE', '$DB_TYPE');|g" /config/www/tt-rss/config.php
    [[ "${DB_HOST}" ]] && sed -i "s|\s*define('DB_HOST',.*|\tdefine('DB_HOST', '$DB_HOST');|g" /config/www/tt-rss/config.php
    [[ "${DB_USER}" ]] && sed -i "s|\s*define('DB_USER',.*|\tdefine('DB_USER', '$DB_USER');|g" /config/www/tt-rss/config.php
    [[ "${DB_NAME}" ]] && sed -i "s|\s*define('DB_NAME',.*|\tdefine('DB_NAME', '$DB_NAME');|g" /config/www/tt-rss/config.php
    [[ "${DB_PASS}" ]] && sed -i "s|\s*define('DB_PASS',.*|\tdefine('DB_PASS', '$DB_PASS');|g" /config/www/tt-rss/config.php
    [[ "${DB_PORT}" ]] && sed -i "s|\s*define('DB_PORT',.*|\tdefine('DB_PORT', '$DB_PORT');|g" /config/www/tt-rss/config.php
    [[ "${MYSQL_CHARSET}" ]] && sed -i "s|\s*define('MYSQL_CHARSET',.*|\tdefine('MYSQL_CHARSET', '$MYSQL_CHARSET');|g" /config/www/tt-rss/config.php
    [[ "${SELF_URL_PATH}" ]] && sed -i "s|\s*define('SELF_URL_PATH',.*|\tdefine('SELF_URL_PATH', '$SELF_URL_PATH');|g" /config/www/tt-rss/config.php
    [[ "${SINGLE_USER_MODE}" ]] && sed -i "s|\s*define('SINGLE_USER_MODE',.*|\tdefine('SINGLE_USER_MODE', '$SINGLE_USER_MODE');|g" /config/www/tt-rss/config.php
    [[ "${SIMPLE_UPDATE_MODE}" ]] && sed -i "s|\s*define('SIMPLE_UPDATE_MODE',.*|\tdefine('SIMPLE_UPDATE_MODE', '$SIMPLE_UPDATE_MODE');|g" /config/www/tt-rss/config.php
    [[ "${PHP_EXECUTABLE}" ]] && sed -i "s|\s*define('PHP_EXECUTABLE',.*|\tdefine('PHP_EXECUTABLE', '$PHP_EXECUTABLE');|g" /config/www/tt-rss/config.php
    [[ "${LOCK_DIRECTORY}" ]] && sed -i "s|\s*define('LOCK_DIRECTORY',.*|\tdefine('LOCK_DIRECTORY', '$LOCK_DIRECTORY');|g" /config/www/tt-rss/config.php
    [[ "${CACHE_DIR}" ]] && sed -i "s|\s*define('CACHE_DIR',.*|\tdefine('CACHE_DIR', '$CACHE_DIR');|g" /config/www/tt-rss/config.php
    [[ "${ICONS_DIR}" ]] && sed -i "s|\s*define('ICONS_DIR',.*|\tdefine('ICONS_DIR', '$ICONS_DIR');|g" /config/www/tt-rss/config.php
    [[ "${ICONS_URL}" ]] && sed -i "s|\s*define('ICONS_URL',.*|\tdefine('ICONS_URL', '$ICONS_URL');|g" /config/www/tt-rss/config.php
    [[ "${AUTH_AUTO_CREATE}" ]] && sed -i "s|\s*define('AUTH_AUTO_CREATE',.*|\tdefine('AUTH_AUTO_CREATE', '$AUTH_AUTO_CREATE');|g" /config/www/tt-rss/config.php
    [[ "${AUTH_AUTO_LOGIN}" ]] && sed -i "s|\s*define('AUTH_AUTO_LOGIN',.*|\tdefine('AUTH_AUTO_LOGIN', '$AUTH_AUTO_LOGIN');|g" /config/www/tt-rss/config.php
    [[ "${FORCE_ARTICLE_PURGE}" ]] && sed -i "s|\s*define('FORCE_ARTICLE_PURGE',.*|\tdefine('FORCE_ARTICLE_PURGE', '$FORCE_ARTICLE_PURGE');|g" /config/www/tt-rss/config.php
    [[ "${SPHINX_SERVER}" ]] && sed -i "s|\s*define('SPHINX_SERVER',.*|\tdefine('SPHINX_SERVER', '$SPHINX_SERVER');|g" /config/www/tt-rss/config.php
    [[ "${SPHINX_INDEX}" ]] && sed -i "s|\s*define('SPHINX_INDEX',.*|\tdefine('SPHINX_INDEX', '$SPHINX_INDEX');|g" /config/www/tt-rss/config.php
    [[ "${ENABLE_REGISTRATION}" ]] && sed -i "s|\s*define('ENABLE_REGISTRATION',.*|\tdefine('ENABLE_REGISTRATION', '$ENABLE_REGISTRATION');|g" /config/www/tt-rss/config.php
    [[ "${REG_NOTIFY_ADDRESS}" ]] && sed -i "s|\s*define('REG_NOTIFY_ADDRESS',.*|\tdefine('REG_NOTIFY_ADDRESS', '$REG_NOTIFY_ADDRESS');|g" /config/www/tt-rss/config.php
    [[ "${REG_MAX_USERS}" ]] && sed -i "s|\s*define('REG_MAX_USERS',.*|\tdefine('REG_MAX_USERS', '$REG_MAX_USERS');|g" /config/www/tt-rss/config.php
    [[ "${SESSION_COOKIE_LIFETIME}" ]] && sed -i "s|\s*define('SESSION_COOKIE_LIFETIME',.*|\tdefine('SESSION_COOKIE_LIFETIME', '$SESSION_COOKIE_LIFETIME');|g" /config/www/tt-rss/config.php
    [[ "${SMTP_FROM_NAME}" ]] && sed -i "s|\s*define('SMTP_FROM_NAME',.*|\tdefine('SMTP_FROM_NAME', '$SMTP_FROM_NAME');|g" /config/www/tt-rss/config.php
    [[ "${SMTP_FROM_ADDRESS}" ]] && sed -i "s|\s*define('SMTP_FROM_ADDRESS',.*|\tdefine('SMTP_FROM_ADDRESS', '$SMTP_FROM_ADDRESS');|g" /config/www/tt-rss/config.php
    [[ "${DIGEST_SUBJECT}" ]] && sed -i "s|\s*define('DIGEST_SUBJECT',.*|\tdefine('DIGEST_SUBJECT', '$DIGEST_SUBJECT');|g" /config/www/tt-rss/config.php
    [[ "${CHECK_FOR_UPDATES}" ]] && sed -i "s|\s*define('CHECK_FOR_UPDATES',.*|\tdefine('CHECK_FOR_UPDATES', '$CHECK_FOR_UPDATES');|g" /config/www/tt-rss/config.php
    [[ "${ENABLE_GZIP_OUTPUT}" ]] && sed -i "s|\s*define('ENABLE_GZIP_OUTPUT',.*|\tdefine('ENABLE_GZIP_OUTPUT', '$ENABLE_GZIP_OUTPUT');|g" /config/www/tt-rss/config.php
    [[ "${PLUGINS}" ]] && sed -i "s|\s*define('PLUGINS',.*|\tdefine('PLUGINS', '$PLUGINS');|g" /config/www/tt-rss/config.php
    [[ "${LOG_DESTINATION}" ]] && sed -i "s|\s*define('LOG_DESTINATION',.*|\tdefine('LOG_DESTINATION', '$LOG_DESTINATION');|g" /config/www/tt-rss/config.php
fi

# permissions
chown -R abc:abc \
	/config/www \
    /var/www/
